// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Channel
    {
        [DataMember(Name = "id")]
        public I128 Id;
        [DataMember(Name = "name")]
        public string Name;

        public Channel(
            I128 Id,
            string Name
        )
        {
            this.Id = Id;
            this.Name = Name;
        }

        public Channel()
        {
            this.Name = "";
        }
    }
}
