// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class FriendRequest
    {
        [DataMember(Name = "hash")]
        public ulong Hash;
        [DataMember(Name = "user_a")]
        public SpacetimeDB.Identity UserA;
        [DataMember(Name = "user_b")]
        public SpacetimeDB.Identity UserB;

        public FriendRequest(
            ulong Hash,
            SpacetimeDB.Identity UserA,
            SpacetimeDB.Identity UserB
        )
        {
            this.Hash = Hash;
            this.UserA = UserA;
            this.UserB = UserB;
        }

        public FriendRequest()
        {
        }
    }
}
