// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Member
    {
        [DataMember(Name = "user_id")]
        public SpacetimeDB.Identity UserId;
        [DataMember(Name = "channel_id")]
        public I128 ChannelId;

        public Member(
            SpacetimeDB.Identity UserId,
            I128 ChannelId
        )
        {
            this.UserId = UserId;
            this.ChannelId = ChannelId;
        }

        public Member()
        {
        }
    }
}
