// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AcceptFriendHandler(ReducerEventContext ctx, string userName);
        public event AcceptFriendHandler? OnAcceptFriend;

        public void AcceptFriend(string userName)
        {
            conn.InternalCallReducer(new Reducer.AcceptFriend(userName), this.SetCallReducerFlags.AcceptFriendFlags);
        }

        public bool InvokeAcceptFriend(ReducerEventContext ctx, Reducer.AcceptFriend args)
        {
            if (OnAcceptFriend == null) return false;
            OnAcceptFriend(
                ctx,
                args.UserName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AcceptFriend : Reducer, IReducerArgs
        {
            [DataMember(Name = "user_name")]
            public string UserName;

            public AcceptFriend(string UserName)
            {
                this.UserName = UserName;
            }

            public AcceptFriend()
            {
                this.UserName = "";
            }

            string IReducerArgs.ReducerName => "accept_friend";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AcceptFriendFlags;
        public void AcceptFriend(CallReducerFlags flags) => AcceptFriendFlags = flags;
    }
}
