// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddFriendHandler(ReducerEventContext ctx, SpacetimeDB.Identity userId);
        public event AddFriendHandler? OnAddFriend;

        public void AddFriend(SpacetimeDB.Identity userId)
        {
            conn.InternalCallReducer(new Reducer.AddFriend(userId), this.SetCallReducerFlags.AddFriendFlags);
        }

        public bool InvokeAddFriend(ReducerEventContext ctx, Reducer.AddFriend args)
        {
            if (OnAddFriend == null) return false;
            OnAddFriend(
                ctx,
                args.UserId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddFriend : Reducer, IReducerArgs
        {
            [DataMember(Name = "user_id")]
            public SpacetimeDB.Identity UserId;

            public AddFriend(SpacetimeDB.Identity UserId)
            {
                this.UserId = UserId;
            }

            public AddFriend()
            {
            }

            string IReducerArgs.ReducerName => "add_friend";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddFriendFlags;
        public void AddFriend(CallReducerFlags flags) => AddFriendFlags = flags;
    }
}
