// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddFriendHandler(ReducerEventContext ctx, string userName);
        public event AddFriendHandler? OnAddFriend;

        public void AddFriend(string userName)
        {
            conn.InternalCallReducer(new Reducer.AddFriend(userName), this.SetCallReducerFlags.AddFriendFlags);
        }

        public bool InvokeAddFriend(ReducerEventContext ctx, Reducer.AddFriend args)
        {
            if (OnAddFriend == null) return false;
            OnAddFriend(
                ctx,
                args.UserName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddFriend : Reducer, IReducerArgs
        {
            [DataMember(Name = "user_name")]
            public string UserName;

            public AddFriend(string UserName)
            {
                this.UserName = UserName;
            }

            public AddFriend()
            {
                this.UserName = "";
            }

            string IReducerArgs.ReducerName => "add_friend";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddFriendFlags;
        public void AddFriend(CallReducerFlags flags) => AddFriendFlags = flags;
    }
}
