// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddUserHandler(ReducerEventContext ctx, string channel, string userName);
        public event AddUserHandler? OnAddUser;

        public void AddUser(string channel, string userName)
        {
            conn.InternalCallReducer(new Reducer.AddUser(channel, userName), this.SetCallReducerFlags.AddUserFlags);
        }

        public bool InvokeAddUser(ReducerEventContext ctx, Reducer.AddUser args)
        {
            if (OnAddUser == null) return false;
            OnAddUser(
                ctx,
                args.Channel,
                args.UserName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddUser : Reducer, IReducerArgs
        {
            [DataMember(Name = "channel")]
            public string Channel;
            [DataMember(Name = "user_name")]
            public string UserName;

            public AddUser(
                string Channel,
                string UserName
            )
            {
                this.Channel = Channel;
                this.UserName = UserName;
            }

            public AddUser()
            {
                this.Channel = "";
                this.UserName = "";
            }

            string IReducerArgs.ReducerName => "add_user";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddUserFlags;
        public void AddUser(CallReducerFlags flags) => AddUserFlags = flags;
    }
}
