// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddUserHandler(ReducerEventContext ctx, I128 channelId, SpacetimeDB.Identity userId);
        public event AddUserHandler? OnAddUser;

        public void AddUser(I128 channelId, SpacetimeDB.Identity userId)
        {
            conn.InternalCallReducer(new Reducer.AddUser(channelId, userId), this.SetCallReducerFlags.AddUserFlags);
        }

        public bool InvokeAddUser(ReducerEventContext ctx, Reducer.AddUser args)
        {
            if (OnAddUser == null) return false;
            OnAddUser(
                ctx,
                args.ChannelId,
                args.UserId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddUser : Reducer, IReducerArgs
        {
            [DataMember(Name = "channel_id")]
            public I128 ChannelId;
            [DataMember(Name = "user_id")]
            public SpacetimeDB.Identity UserId;

            public AddUser(
                I128 ChannelId,
                SpacetimeDB.Identity UserId
            )
            {
                this.ChannelId = ChannelId;
                this.UserId = UserId;
            }

            public AddUser()
            {
            }

            string IReducerArgs.ReducerName => "add_user";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddUserFlags;
        public void AddUser(CallReducerFlags flags) => AddUserFlags = flags;
    }
}
