// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateChannelHandler(ReducerEventContext ctx, string channelName);
        public event CreateChannelHandler? OnCreateChannel;

        public void CreateChannel(string channelName)
        {
            conn.InternalCallReducer(new Reducer.CreateChannel(channelName), this.SetCallReducerFlags.CreateChannelFlags);
        }

        public bool InvokeCreateChannel(ReducerEventContext ctx, Reducer.CreateChannel args)
        {
            if (OnCreateChannel == null) return false;
            OnCreateChannel(
                ctx,
                args.ChannelName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateChannel : Reducer, IReducerArgs
        {
            [DataMember(Name = "channel_name")]
            public string ChannelName;

            public CreateChannel(string ChannelName)
            {
                this.ChannelName = ChannelName;
            }

            public CreateChannel()
            {
                this.ChannelName = "";
            }

            string IReducerArgs.ReducerName => "create_channel";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateChannelFlags;
        public void CreateChannel(CallReducerFlags flags) => CreateChannelFlags = flags;
    }
}
