// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SendMessageHandler(ReducerEventContext ctx, string text, string channel);
        public event SendMessageHandler? OnSendMessage;

        public void SendMessage(string text, string channel)
        {
            conn.InternalCallReducer(new Reducer.SendMessage(text, channel), this.SetCallReducerFlags.SendMessageFlags);
        }

        public bool InvokeSendMessage(ReducerEventContext ctx, Reducer.SendMessage args)
        {
            if (OnSendMessage == null) return false;
            OnSendMessage(
                ctx,
                args.Text,
                args.Channel
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SendMessage : Reducer, IReducerArgs
        {
            [DataMember(Name = "text")]
            public string Text;
            [DataMember(Name = "channel")]
            public string Channel;

            public SendMessage(
                string Text,
                string Channel
            )
            {
                this.Text = Text;
                this.Channel = Channel;
            }

            public SendMessage()
            {
                this.Text = "";
                this.Channel = "";
            }

            string IReducerArgs.ReducerName => "send_message";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SendMessageFlags;
        public void SendMessage(CallReducerFlags flags) => SendMessageFlags = flags;
    }
}
