// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class FriendRequestHandle : RemoteTableHandle<EventContext, FriendRequest>
        {
            protected override string RemoteTableName => "friend_request";

            public sealed class HashUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(FriendRequest row) => row.Hash;

                public HashUniqueIndex(FriendRequestHandle table) : base(table) { }
            }

            public readonly HashUniqueIndex Hash;

            internal FriendRequestHandle(DbConnection conn) : base(conn)
            {
                Hash = new(this);
            }
        }

        public readonly FriendRequestHandle FriendRequest;
    }
}
