// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class FriendHandle : RemoteTableHandle<EventContext, Friend>
        {
            protected override string RemoteTableName => "friend";

            internal FriendHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly FriendHandle Friend;
    }
}
